spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/starbag_inventory
    username: inventory_user
    password: inventory123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8882
  servlet:
    context-path: /api/v1

product:
  service:
    url: http://172.31.72.154:8082/api/v1/products