services:
  order-management-service:
    build: .
    container_name: order-management-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://order-management-db.c36keqki0gue.eu-north-1.rds.amazonaws.com:3306/order_management_db?useSSL=true&requireSSL=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: order123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped